FROM neo4j:4.2.1
ENV NEO4J_AUTH="neo4j/Abcd1234"
ENV NEO4J_dbms_memory_heap_initial__size='4g'
ENV NEO4J_dbms_memory_heap_max__size='4g'
ENV NEO4J_dbms_memory_pagecache_size='4g'
ENV NEO4JLABS_PLUGINS='["apoc", "graph-data-science"]'
VOLUME ['/data']